/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://7vrhjsrdffd2pinmi6t4oevzsi.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mc5q2rmldrcgpi2xsifpnphncq",
    "aws_content_delivery_bucket": "kmc1-20230926172732-hostingbucket-staging",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d3bb5gs8m3ffjd.cloudfront.net"
};


export default awsmobile;
